// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPdZecpS45-kaG5UgTK5WSraxVNEOpH0',
    appId: '1:579739380756:web:c0de6b8270554421254b01',
    messagingSenderId: '579739380756',
    projectId: 'doctorcrudweb',
    authDomain: 'doctorcrudweb.firebaseapp.com',
    storageBucket: 'doctorcrudweb.firebasestorage.app',
    measurementId: 'G-GN229T7NJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZomQVIqJ88S9qmBwifRn-l6SIYoe_fE',
    appId: '1:579739380756:android:bddf597863980798254b01',
    messagingSenderId: '579739380756',
    projectId: 'doctorcrudweb',
    storageBucket: 'doctorcrudweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbR8lDKCfSOBTq61rddn2l8_jkiR6cI7U',
    appId: '1:579739380756:ios:b60c5169f1c7fbb6254b01',
    messagingSenderId: '579739380756',
    projectId: 'doctorcrudweb',
    storageBucket: 'doctorcrudweb.firebasestorage.app',
    iosBundleId: 'com.example.doctorCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbR8lDKCfSOBTq61rddn2l8_jkiR6cI7U',
    appId: '1:579739380756:ios:b60c5169f1c7fbb6254b01',
    messagingSenderId: '579739380756',
    projectId: 'doctorcrudweb',
    storageBucket: 'doctorcrudweb.firebasestorage.app',
    iosBundleId: 'com.example.doctorCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPdZecpS45-kaG5UgTK5WSraxVNEOpH0',
    appId: '1:579739380756:web:d325c0dc38a8569d254b01',
    messagingSenderId: '579739380756',
    projectId: 'doctorcrudweb',
    authDomain: 'doctorcrudweb.firebaseapp.com',
    storageBucket: 'doctorcrudweb.firebasestorage.app',
    measurementId: 'G-Z8R16W53F1',
  );
}
